"""
Gradio demo app — Unmasking Synthetic Images.

Entry point for HuggingFace Spaces (app_file: demo/app.py).
Wraps MoEPipeline for single-image forensic classification and attribution.

HF Space: https://huggingface.co/spaces/enricoroncuzzi/unmasking-synthetic-images-demo
"""

import sys
from pathlib import Path
from typing import Optional

# Ensure repo root is on sys.path so "from demo.pipeline import ..." resolves
# correctly whether this file is run as "python demo/app.py" (HF Spaces style)
# or as "python -m demo.app" from the repo root.
_DEMO_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _DEMO_DIR.parent
sys.path.insert(0, str(_REPO_ROOT))

import gradio as gr
import matplotlib

matplotlib.use("Agg")  # non-interactive backend, required in server environments
import matplotlib.pyplot as plt

from demo.pipeline import MoEPipeline

# ── Constants ──────────────────────────────────────────────────────────────────

_EXPERT_LABELS = {
    "sd15":     "Stable Diffusion 1.5",
    "sd21":     "Stable Diffusion 2.1",
    "sdxlbase": "SDXL Base",
    "sd35":     "Stable Diffusion 3.5",
    "flux":     "FLUX.1",
}

_STRATEGY = "logit"

_EXAMPLES_DIR = _DEMO_DIR / "examples"

_TITLE = "Unmasking Synthetic Images — Forensic MoE Demo"

_DESCRIPTION = """
Detect whether an image was generated by an AI model and identify which diffusion model produced it.

**How it works:** five ResNet50 experts (each trained on a different SD variant) feed into a
Mixture-of-Experts gating network. The gating weights (*alpha*) reveal which expert "recognises"
the image, attributing it to a specific generator.

**Results (Phase 4 evaluation):**  MoE-Logit achieves **94.1% Balanced Accuracy** on the held-out test set.

[GitHub repo](https://github.com/enricoroncuzzi/unmasking-synthetic-images) ·
[HuggingFace models](https://huggingface.co/enricoroncuzzi/unmasking-synthetic-images-models)
"""

# ── Pipeline preload ───────────────────────────────────────────────────────────
# Loaded at import time so HF Spaces pays the cold-start cost during boot,
# not on the first user click.
PIPELINE = MoEPipeline(device="cpu", strategy=_STRATEGY)


# ── Visualization helpers ──────────────────────────────────────────────────────

def _alpha_bar_chart(
    alpha_weights: dict,
    attributed_source: Optional[str],
) -> plt.Figure:
    """
    Horizontal bar chart of per-expert gating weights.

    The attributed expert bar is highlighted in red; others in steel blue.
    """
    names  = list(alpha_weights.keys())
    values = [alpha_weights[n] for n in names]
    labels = [_EXPERT_LABELS.get(n, n) for n in names]
    colors = [
        "#e05c5c" if n == attributed_source else "#4a90d9"
        for n in names
    ]

    fig, ax = plt.subplots(figsize=(6, 2.8))
    bars = ax.barh(labels, values, color=colors, edgecolor="none", height=0.55)
    ax.set_xlim(0, 1.05)
    ax.set_xlabel("Gating weight (α)", fontsize=9)
    ax.tick_params(axis="y", labelsize=9)
    ax.tick_params(axis="x", labelsize=8)
    ax.spines[["top", "right"]].set_visible(False)

    if attributed_source:
        title = f"Attributed to: {_EXPERT_LABELS.get(attributed_source, attributed_source)}"
    else:
        title = "Expert routing weights"
    ax.set_title(title, fontsize=10, pad=6)

    for bar, val in zip(bars, values):
        x_pos = val + 0.02 if val < 0.88 else val - 0.06
        ax.text(
            x_pos,
            bar.get_y() + bar.get_height() / 2,
            f"{val:.1%}",
            va="center",
            fontsize=8,
            color="#333333",
        )

    fig.tight_layout()
    return fig


# ── Gradio callback ────────────────────────────────────────────────────────────

def analyze(image):
    """
    Main inference callback wired to the Gradio interface.

    Args:
        image : PIL.Image from gr.Image input (None if no image uploaded)

    Returns:
        label_out  : dict for gr.Label  e.g. {"synthetic": 0.97}
        alpha_plot : matplotlib Figure  for gr.Plot
        gradcam_out: PIL.Image          for gr.Image
    """
    if image is None:
        return None, None, None

    result = PIPELINE.predict(image)
    gradcam_img = PIPELINE.gradcam(image)
    alpha_fig = _alpha_bar_chart(result["alpha_weights"], result["attributed_source"])

    label_out = {result["prediction"]: result["confidence"]}
    return label_out, alpha_fig, gradcam_img


# ── Example images ─────────────────────────────────────────────────────────────

def _load_examples() -> list:
    """Returns a list of [image_path] rows for gr.Examples, if available."""
    if not _EXAMPLES_DIR.is_dir():
        return []
    exts = {".jpg", ".jpeg", ".png", ".webp"}
    paths = sorted(
        p for p in _EXAMPLES_DIR.iterdir()
        if p.suffix.lower() in exts
    )
    return [[str(p)] for p in paths]


# ── UI layout ──────────────────────────────────────────────────────────────────

def build_demo() -> gr.Blocks:
    examples = _load_examples()

    with gr.Blocks(title=_TITLE, theme=gr.themes.Soft()) as demo:

        gr.Markdown(f"# {_TITLE}")
        gr.Markdown(_DESCRIPTION)

        with gr.Row():
            # ── Left column: input ───────────────────────────────────────────
            with gr.Column(scale=1):
                image_input = gr.Image(
                    type="pil",
                    label="Upload image (drag & drop or click)",
                )
                analyze_btn = gr.Button("Analyze", variant="primary")

                if examples:
                    gr.Examples(
                        examples=examples,
                        inputs=[image_input],
                        label="Example images",
                    )

            # ── Right column: outputs ────────────────────────────────────────
            with gr.Column(scale=1):
                label_output = gr.Label(
                    num_top_classes=2,
                    label="Prediction",
                )
                alpha_plot = gr.Plot(
                    label="Expert routing weights (α)",
                )
                gradcam_output = gr.Image(
                    type="pil",
                    label="Grad-CAM — where the attributed expert looks",
                )

        # ── Wiring ──────────────────────────────────────────────────────────
        analyze_btn.click(
            fn=analyze,
            inputs=[image_input],
            outputs=[label_output, alpha_plot, gradcam_output],
        )

        # Also trigger on image upload for snappier UX
        image_input.upload(
            fn=analyze,
            inputs=[image_input],
            outputs=[label_output, alpha_plot, gradcam_output],
        )

        gr.Markdown(
            "---\n"
            "*Models hosted on [HuggingFace Hub](https://huggingface.co/enricoroncuzzi/unmasking-synthetic-images-models). "
            "Running MoE-Logit strategy on CPU.*"
        )

    return demo


demo = build_demo()

if __name__ == "__main__":
    demo.launch()
